services:
  amazon-braket:
    image: aws-braket-notebook
    container_name: aws-braket-notebook
    working_dir: /home/braket/aws-braket-jupyter
    build:
      context: ./
      dockerfile: ./Dockerfile # production environment
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./example:/home/braket/aws-braket-jupyter
      - $HOME/.aws/:/root/.aws/
    ports:
      - 8888:8889
    restart: unless-stopped